### ISSUE TITLE
Update to 0.10.1 release

### ISSUE THREAD

**Issue by bryanjhv** [Mogztter/opal-node-runtime#1]
Both `0.10.0` and `0.10.1` are now stable, and maybe it's better to have them available instead of integration releases.

**Comment by Mogztter** [comment]
Hello @bryanjhv 
Yes I just need https://github.com/opal/opal/pull/1456 to be merged then I can switch back to Opal master.

I will publish a release for `0.10.1`

**Comment by bryanjhv** [comment]
Oh, you're right. Waiting for that. :smile:

**Comment by Mogztter** [comment]
Version 0.10.1 is now available (without opal/opal#1456 fix). Let me know if this is working for you.

**Comment by bryanjhv** [comment]
It's working. Or at least the test suite passes. I'll try to check another things and tell you if anything is wrong, i.e. for me.

**Comment by Mogztter** [comment]
Great thanks :smile:
